config/routes.rb
Rails.application.routes.draw do

  resources :contracts do
    resources :items
  end

  root 'contracts#index'

  get 'contracts/index'
  get 'contracts/new'

  match '/concreate', to: 'contracts#new', via: 'get'

end

app/models/contract_haikibutsu.rb
class ContractHaikibutsu < ActiveRecord::Base
  belongs_to :contract
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :contract

  validates :item,  presence: true
  validates :suryo, presence: true
  validates :tanka,  presence: true

end

app/models/validation/contract/contract_kikan_validation.rb
# -*- coding: utf-8 -*-

# 契約期間_終了年月日の検証
module Validation::Contract::ContractKikanValidation
#  include DataMapper::Validations
  include Validation::DefineGroup

  define_validation_group {|contexts|
    lambda {|m|
      validates_with_method :base, method: :contract_kikan_reverse? #, when: contexts
    }
  }

#  def contract_kikan_reverse?
#    return true if self.itakustart.nil? || ! self.itakustart.is_a?(Date)
#    if self.itakustart.to_date > itakuend.to_date
#      true
#    else
#      return [false, ::I18n.t(:invalid_contract_kikan, scope: "validation.contract.contract_kikan")]
#    end
#  end
end

app/models/validation/contract/incident_validation.rb
# coding: utf-8

# 契約付帯情報整合性チェック
module Validation::Contract::IncidentValidation
#  include DataMapper::Validations
#  include Validation::DefineGroup

#  include Validation::Contract::ContractKikanValidation
#
#
#  define_validation_group {|contexts|
#    lambda {|m|
#      validates_with_method :base, method: :contract_kikan_reverse? #, when: contexts, if: :scratch_register?
#    }
#  }

  def contract_kikan_reverse?
    return true if self.itakustart.nil? || ! self.itakustart.is_a?(Date)
    if self.itakustart.to_date > itakuend.to_date
      true
    else
      #return [false, ::I18n.t(:invalid_contract_kikan, scope: "validation.contract.contract_kikan")]
      return
    end
  end

end

app/models/validation/define_group.rb
# -*- coding: utf-8 -*-

module Validation::DefineGroup
  def self.included(base)
    base.extend ClassMethods
  end

  module ClassMethods
    def define_validation_group(&block)
      const_set(:VALIDATION_GROUP, block)
    end
  end
end

app/models/validation/loader.rb
# -*- coding: utf-8 -*-

module Validation::Loader
  def self.included(base)
    base.extend ClassMethods
  end

  module ClassMethods
    # mod      - 検証module
    # contexts - modによる検証をを有効にするcontextを指定
    #
    # Example
    #
    #   class Contract
    #     include Validation::Loader
    #
    #     load_validation_group Validation::Contract::TemporaryStatusValidation, [:temporary]
    #
    #     def valid_for_persist
    #       self.valid? # => 暗黙に:defaultコンテキストでの検証となる
    #       self.valid?(:temporary) # => Validation::Contract::TemporaryStatusValidationの持つ検証が実行される
    #     end
    def load_validation_group(contexts)#(mod, contexts)
     # include mod
     # class_eval &(mod.const_get(:VALIDATION_GROUP).call(contexts))
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  #2016/02/10 add
  #use Rails::DataMapper::Middleware::IdentityMap
  #2016/02/10 add end

  protect_from_forgery with: :exception
end

app/controllers/contract_haikibutsus_controller.rb
class ContractHaikibutsusController < ApplicationController



  def create
    @contract = Contract.find(params[:contract_id])
    @contracthaikibutsu = @contract.contracthaikibutsus.create(haikibutsu_params)
    redirect_to contract_path(@contract)
  end

  private
  def haikibutsu_params
    params.require(:contracthaikibutsu).permit(:haikibutsu, :suryo, :tanka)
  end

end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController

  def new
   @contract = Contract.new
  end

  def create
    @contract = Contract.new(contract_params)
    #byebug
    if @contract.save
      #sign_in @user
      flash[:success] = "Insert OK!!"
      redirect_to @contract
      #byebug
    else
      render 'new'
    end
  end

  def index

# branch prep_search 2015/12/02

    sql = 'SELECT C.* FROM contracts C'


    conditionflg = 0

    if params[:search].present? && params[:searchsaki].present?
#      jyoken = params[:search]
#      sql = sql + ' WHERE itakumoto LIKE ?', "%#{jyoken}%"
#      conditionflg = 1

#     if params[:searchsaki]
      jyoken = params[:search]
      jyoken2 = params[:searchsaki]
#      sql = sql + ' WHERE itakumoto LIKE ?', "%#{jyoken}%"
#      sql = sql + ' AND itakusaki LIKE ?', "%#{jyoken2}%"
#      sql = sql + ' WHERE itakumoto LIKE ?', "%#{jyoken}%", ' AND itakusaki LIKE ?', "%#{jyoken2}%"
      sql = sql + ' WHERE itakumoto LIKE ? AND itakusaki LIKE ?', "%#{jyoken}%", "%#{jyoken2}%"
#      sql = sql + ' WHERE itakumoto LIKE "%1%" AND itakusaki LIKE "%2%"'
#     else
#      # do nothing
#     end
      #byebug
      #@contracts = Contract.search(params[:search])
      #@contracts = Contract.paginate_by_sql(sql,:page => params[:page], :per_page => 5)
      conditionflg = 1
# branch prep_search 2015/12/02 end
    else

     if params[:searchsaki].present?
#      jyoken = params[:search]
      jyoken2 = params[:searchsaki]
      sql = sql + ' WHERE itakusaki LIKE ?', "%#{jyoken2}%"
      conditionflg = 1
     elsif params[:search].present?
      jyoken = params[:search]
      #jyoken2 = params[:searchsaki]
      sql = sql + ' WHERE itakumoto LIKE ?', "%#{jyoken}%"
      conditionflg = 1
     else

     end

    end

    if conditionflg == 1
     @contracts = Contract.paginate_by_sql(sql,:page => params[:page], :per_page => 5)
    else
     @contracts = Contract.paginate(page: params[:page],:per_page => 5)
    end

  end

  def show
    @contract = Contract.find(params[:id])
    #2016/02/10 add seigoseierror
    #flash.now[:error] = build_error_messages

  end

  def edit
   @contract = Contract.find(params[:id])
  end

  def update
    @contract = Contract.find_by_id(params[:id])

    if @contract.update_attributes(contract_params)
      flash[:success] = "Profile updated"
      redirect_to @contract
    else
      #flash.now[:error] = build_error_messages
      render 'edit'
    end

#  @contract = Contract.find_by_id(params[:id])
#  @contract.update_attributes(contract_params)
#  flash[:success] = "Product donated!"

  end

  def destroy
    Contract.find(params[:id]).destroy
    flash[:success] = "Contract deleted."
    redirect_to contracts_url
  end

  #2016/02/10 add method
  def build_error_messages
    messages = []
    messages += @contract.errors[:base] unless @contract.valid?#(:contract_detail)
    messages
#    #messages = ["kikan error"]
  end

  private

    def contract_params
      params.require(:contract).permit(:itakumoto, :itakusaki, :itakustart, :itakuend)
    end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def create
    @contract = Contract.find(params[:contract_id])
    @item = @contract.items.create(item_params)
    redirect_to contract_path(@contract)
  end

  def destroy
    @contract = Contract.find(params[:contract_id])
    @item = @contract.items.find(params[:id])
    @item.destroy
    redirect_to contract_path(@contract)
  end

  private
  def item_params
    params.require(:item).permit(:item, :suryo, :tanka)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contract_haikibutsus_helper.rb
module ContractHaikibutsusHelper
end

app/helpers/contracts_helper.rb
module ContractsHelper

  def current_contract
    @current_contract ||= Contract.find(params[:id])
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/contracts/edit.html.erb
<br>
<h2>Update Contract Info</h2>

<div class="row">
  <div class="span6 offset3">
      <%= render "/shared/error_seigosei_messages", error_messages: flash[:error] %>
    <%= form_for(@contract) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :itakumoto %>
<%= render 'shared/label/gyoshu', gyoshu_division: 'HAISHUTSU' %>
      <%= f.text_field :itakumoto %>

      <%= f.label :itakusaki %>
<%= render 'shared/label/gyoshu', gyoshu_division: 'SHORI' %>
      <%= f.text_field :itakusaki %>

      <%= f.label :itakustart %>
      <%= f.text_field :itakustart %>

      <%= f.label :itakuend %>
      <%= f.text_field :itakuend %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>


      <li><%= link_to "Cancel Back", current_contract %></li>
      <li><%= link_to "ContractsList", root_path %></li>

<%= link_to 'Cancel Back', current_contract, class: 'btn btn-left' %>
<%= link_to 'ContractsList', root_path, class: 'btn btn-left btn-inverse' %>

    <% end %>

  </div>
</div>

app/views/contracts/index.html.erb
<br>
<h2>Contracts You have to do with</h2>
<p>Find me in app/views/contracts/index.html.erb</p>

<%= form_tag root_path, :method => 'get' do %>
  <p>
    itakumoto_search
    <%= text_field_tag :search, params[:search] %>
    itakusaki_search
    <%= text_field_tag :searchsaki, params[:searchsaki] %>
    <%= submit_tag "Search", :itakumoto => nil ,:itakusaki => nil  %>
  </p>
<% end %>


<%= will_paginate %>

<ul>
  <table>
   <tr>
    <td width=250>
      itakumoto
<%= render 'shared/label/gyoshu', gyoshu_division: 'HAISHUTSU' %>
    </td>
    <td width=250>
      itakusaki
<%= render 'shared/label/gyoshu', gyoshu_division: 'SHORI' %>
    </td>
   </tr>
  </table>
</ul>

<ul class="contracts">
  <%#= render @contracts %>
<% @contracts.each do |contract| %>

  <%#= gravatar_for contract, size: 52 %>
  <%#= link_to contract.itakumoto, contract %>

 
  <table border = "0">

   <tr>
    <td width=250>
     <%= contract.itakumoto %>
    </td>
    <td width=250>
     <%= contract.itakusaki %>
    </td>
    <td width=130>
     <%= link_to "Refer&Haikibutsu", contract %>
    </td>
    <td width=40>
     <%= link_to "Delete", contract, method: :delete,
                                  data: { confirm: "You sure?" } %>
    </td>
   </tr>
  </table>

<% end %>


</ul>

<%= will_paginate %>

<h2>
<li><%= link_to "NewContract", concreate_path %></li>
<%= link_to 'NewContract', concreate_path, class: 'btn btn-left btn-inverse' %>
</h2>

app/views/contracts/new.html.erb
<br>
<h2>Create New Contract</h2>
<p>Find me in app/views/contracts/new.html.erb</p>


<div class="row">
  <div class="span6 offset3">
    <%= form_for(@contract) do |f| %>

      <%= render 'shared/error_messages', object: f.object %>

      <!--<%= f.label :itakumoto %>-->
      <label class="control-label width-auto">itakumoto <span class="required"><font color = 'red'>*neccesary</font></span></label>
<%= render 'shared/label/gyoshu', gyoshu_division: 'HAISHUTSU' %>
      <%= f.text_field :itakumoto %>
      <label class="control-label width-auto">   <span class="required">test comment  when saisei baikyakusaki</span></label>

      <!--<%= f.label :itakusaki %>-->
      <label class="control-label width-auto">itakusaki<span class="required"><font color = 'red'>*neccesary</font></span></label>
<%= render 'shared/label/gyoshu', gyoshu_division: 'SHORI' %>
      <%= f.text_field :itakusaki %>

      <%= f.label :itakustart %>
      <%= f.text_field :itakustart %>

      <%= f.label :itakuend %>
      <%= f.text_field :itakuend %>


      <%= f.submit "Create Contract", class: "btn btn-large btn-primary" %>

      <%= f.submit "BackToList", {:type => "button", :onClick => "this.form.action=root_path; this.form.submit();"} %>

    <% end %>
  </div>
</div>


<li><%= link_to "Back to ContractsList", root_path %></li>

<%= link_to 'ContractsList', root_path, class: 'btn btn-left btn-inverse' %>

app/views/contracts/show.html.erb
<br>
<h2>Contract Details</h2>
<p>Find me in app/views/contracts/show.html.erb</p>

<%
=begin
%>
<%= @contract.itakumoto %>, <%= @contract.itakusaki %>
<%
=end
%>


<div class="row">
      <%= render "/shared/error_seigosei_messages", error_messages: flash[:error] %>

  <aside class="span8">
    <section>

      <table>
       <tr>
        <td width = '75'>
        itakumoto
        <td></td>
       </tr>
       <tr>
        <td width = '80'>
        <%= render 'shared/label/gyoshu', gyoshu_division: 'HAISHUTSU' %></td>
        <td><%= @contract.itakumoto %></td>
       </tr>
       <tr>
        <td width = '75'>
        itakusaki
        <td></td>
       </tr>
       <tr>
        <td width = '80'>
        <%= render 'shared/label/gyoshu', gyoshu_division: 'SHORI' %></td>
        <td><%= @contract.itakusaki %></td>
       </tr>
      </table>
      <br>
      <table>
       <tr>
        <td>
        itakustart:</td><td width = '100'><%= @contract.itakustart %></td>

        <td>
        itakuend:</td><td width = '100'><%= @contract.itakuend %></td>

       </tr>
      </table>

    </section>
  </aside>


</div>

<br><br>

  contract_haikibutsu

    <%= render @contract.items %>

<br><br>
  Add a haikibutsu:
  <%= render "items/form" %>


<div class="link">
<h4>
<li><%= link_to "ChangeThis", edit_contract_path(current_contract) %></li>
<li><%= link_to "ContractsList", root_path %></li>
<br><br>
<%= link_to 'ChangeThis', edit_contract_path, class: 'btn btn-left' %>
<%= link_to 'BackToList', root_path, class: 'btn btn-left btn-inverse' %>
</h4>
</div>

     <%= link_to "delete", current_contract, method: :delete,
                                  data: { confirm: "You sure?" } %>

app/views/items/_form.html.erb
  <%= form_for([@contract, @contract.items.build]) do |f| %>

      <%= render 'shared/error_messages', object: f.object %>


      <table>
       <tr>
        <td width = '150'>haikibutsu</td>

        <td width = '75'>suryo</td>

        <td width = '120'>tanka</td>
       </tr>

       <tr>
        <td width = '150'><%= f.text_field :item %></td>

        <td width = '75'><%= f.text_field :suryo %></td>

        <td width = '120'><%= f.text_field :tanka %></td>
       </tr>

      </table>

    <p>
      <%= f.submit %>
    </p>

  <% end %>

app/views/items/_item.html.erb
    <table>
      <tr>
        <td width = '150'><%= item.item %></td>
        <td width = '75'><%= item.suryo %></td>
        <td width = '120'><%= item.tanka %></td>
        <td width=40>
        <%= link_to "DeleteHaikibutsu", [item.contract, item], method: :delete,
                                  data: { confirm: "You sure?" } %>
      </tr>
    </table>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="https://www.e-reverse.com/">e-reverse.com</a>
  </small>
  <nav>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "er-contract", '#', id: "logo" %>
      <nav>
        <!--<ul role="navigation" class="nav" style="">-->
        <ul class="nav pull-right">
          <li><%= link_to "ERC Hachi", '#' %></li>
          <li><%= link_to "SoshikiSelect", '#' %></li>
          <li><%= link_to "Manual", '#' %></li>
        </ul>
      </nav>
    </div>
  </div>

  <div class="navbar-inner user-info">
    <div class="container">
      <nav>
        <ul class="nav pull-left">
          <li><%= link_to "Tsuchi", '#' %></li>
          <li><%= link_to "NewContract", concreate_path %></li>
          <li><%= link_to "Syonin_Irai", '#' %></li>

            <li><%= link_to "Users", '#' %></li>

            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Master <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "tanka", '#' %></li>
                <li><%= link_to "yakkan", '#' %></li>
                <li class="divider"></li>
                <li><%= link_to "shobun_noryoku", '#' %></li>
                <li><%= link_to "saisyu_shobun", '#' %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", '#' %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "LogOut", '#' %></li>

        </ul>
      </nav>
    </div>

  </div>

</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>YokoCon</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_seigosei_messages.html.erb
<% if error_messages.present? %>
  <div class="alert alert-error">
   <ul>
    <% error_messages.each do |error_message| %>
     <li><%= error_message %></li>
    <% end %>
   </ul>
  </div>
<% end %>

app/views/shared/label/_gyoshu.html.erb
<% if gyoshu_division == 'HAISHUTSU' %><span class="label label-success">HAISHUTSU</span><% end %>
<% if gyoshu_division == 'UNPAN' %><span class="label label-collection-delivery">UNPAN</span><% end %>
<% if gyoshu_division == 'SHOBUN' %><span class="label label-disposal">SYOBUN</span><% end %>
<% if gyoshu_division == 'SHORI' %><span class="label label-warning">SHORI</span><% end %>